title: Tianee Carnakie
description: Data Analyst | SQL | R | Tableau
theme: minima

author:
  name: Tianee Carnakie
  email: tianeecarnakie@gmail.com

header_pages:
  - index.md
  - projects/bellabeat.md
